name: slingshot
channels:
 - bioconda
 - conda-forge
 - defaults
dependencies:
 - r-base
 - bioconductor-biomart
 - bioconductor-flowpeaks
 - bioconductor-genomeinfodbdata
 - bioconductor-singlecellexperiment
 - bioconductor-sva
 - bioconductor-slingshot
 - r-devtools
 - r-biocmanager
 - r-data.table
 - r-dplyr
 - r-fields
 - r-igraph
 - r-ineq
 - r-optparse
 - r-rafalib
 - r-rcolorbrewer
 - r-scales
 - r-seurat
 - r-vegan
 - r-hdf5r
 - r-umap
 - r-grr
 - r-pbmcapply
 - wget
